add set -e

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+set -e # fail fast
+
 echo "Installing youtube-dl in "$1"/bin"
 
 mkdir -p foo $1/bin
